version: '3.8'

services:
  kong-database:
    image: postgres:13
    container_name: kong-database
    networks:
      - kong-net
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kongpass
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kong"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  kong-migrations:
    build: .
    container_name: kong-migrations
    depends_on:
      kong-database:
        condition: service_healthy  # Ensures that PostgreSQL is ready to accept connections
    networks:
      - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kongpass
      KONG_PASSWORD: test
    command: "kong migrations bootstrap"
    restart: on-failure

  kong-gateway:
    build: .
    # image: kong/kong-gateway:3.7.1.1
    container_name: kong-gateway
    # command: /bin/sh -c "luarocks install xml2lua && kong start"
    # volumes:
    # - ./soap-transform/:/usr/local/share/lua/5.1/kong/plugins/soap-transform
    depends_on:
      kong-migrations:
        condition: service_started
    networks:
      - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
      # KONG_PLUGINS: "bundled,soap-transform"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"
    restart: always

  # kong-migrations-up:
  #   image: kong/kong-gateway:3.7.1.1
  #   container_name: kong-migrations-up
  #   depends_on:
  #     kong-database:
  #       condition: service_started
  #   networks:
  #     - kong-net
  #   environment:
  #     KONG_DATABASE: postgres
  #     KONG_PG_HOST: kong-database
  #     KONG_PG_PASSWORD: kongpass
  #     KONG_PASSWORD: test
  #   command: "kong migrations up"
  #   restart: on-failure


networks:
  kong-net:
    driver: bridge
